version: 0.2

phases:
  pre_build: 
    commands:
      - echo Logging into ECR...
      - aws ecr get-login-password --region sa-east-1 | docker login --username AWS --password-stdin 735788304992.dkr.ecr.sa-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -f ./.docker/Dockerfile.prod -t demo1 .
      - docker tag demo1:latest 735788304992.dkr.ecr.sa-east-1.amazonaws.com/demo1:latest
  post_build:
    commands:
      - echo Build completed
      - echo Pushing Docker image...
      - docker push 735788304992.dkr.ecr.sa-east-1.amazonaws.com/demo1:latest