version: '3'

services:
  app:
    build: 
      dockerfile: ./.docker/Dockerfile
      context: .
    volumes:
      - .:/uploader/src
    ports:
      - 3000:3000
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET=${AWS_SECRET}
      - S3_NAME=${S3_NAME}
      - S3_URL=${S3_URL}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_CONNECTION=${DATABASE_CONNECTION}
      - USE_AWS=${USE_AWS}
      - UPLOAD_URL=${UPLOAD_URL}
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'